# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 22:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitterscheduler', '0005_auto_20170905_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledtweet',
            options={'ordering': ['time_to_tweet']},
        ),
        migrations.AddField(
            model_name='scheduledtweet',
            name='task_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_sync_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 5, 22, 1, 56, 67091, tzinfo=utc)),
        ),
    ]
